### ISSUE TITLE
Item added to ProcessWire\InputfieldsArray is not an allowed type

### ISSUE THREAD

**Issue by johnnydoe82** [robertweiss/ProcessTranslatePage#6]
Hi there! 
Thanks for this module, looks very promising!
Although, I have a problem after installing: 
"Item added to ProcessWire\InputfieldsArray is not an allowed type"
![Module_ TranslatePage (via Fluency) • localhost](https://user-images.githubusercontent.com/1230322/146359588-0500853f-8639-4e6a-8cc3-bbd423930798.png)

Did I just made some stupid error somewhere? (I have installed and configured fluency before installing ProcessTranslatePage). Processwire version is 3.0.148 and my PHP version is currently 7.4.26.

**Comment by robertweiss** [comment]
Thx for the report! It looks like one of the used inputfield types for the config screen is not installed. Could you do a quick check if you have installed the following inputfields: InputfieldSelect, InputfieldRadios, InputfieldCheckbox, InputfieldASMSelect?

**Comment by johnnydoe82** [comment]
Thx for the quick reply. 
Yes, seems as if I have installed those four inputfields. 

I tried now to update my ProcessWire core. And now it works! With PW 3.0.148 it wasn't, now with PW 3.0.184 it works as expected. Thanks again for this really great module! :)

**Comment by robertweiss** [comment]
Weird, but good to know 😄  I now added this as the required version of processwire in the module info to prevent that error in the future. Thanks for investigating!
