### ISSUE TITLE
Error translating pages with Repeater Matrix

### ISSUE THREAD

**Issue by ivangretsky** [robertweiss/ProcessTranslatePage#7]
Thanks for the wonderful module!

I got an error translating pages with Repeater Matrix field (see the screen shot). We use it for the content builder, so it is essential. Could you please take a look at this bug, @robertweiss ?

![2022-01-11-screenshot-at--21-24-34](https://user-images.githubusercontent.com/6697626/149002627-ccb38b1a-1a10-4b6b-bf02-da6bc00fda22.png)

**Comment by robertweiss** [comment]
Ah ok, there seems to be an issue with the new RepeaterMatrix versions after v5. The class for the field apparently changed from RepeaterField to RepeaterMatrixField, so my parameter type definition does not fit anymore. I just committed a small fix which simply removes that check. Does that work for you?
